export const SEND_MESSAGE = 'SEND_MESSAGE_SUCCESS';
export const START_CONVERSATION = 'START_CONVERSATION_SUCCESS';
export const EDIT_MESSAGE = 'EDIT_MESSAGE_SUCCESS';
export const DELETE_MESSAGE = 'DELETE_MESSAGE_SUCCESS';
export const DELETE_CONVERSATION_SUCCESS = 'DELETE_CONVERSATION_SUCCESS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const LOGOUT = 'LOGOUT';
