version: '3.5'

services:
  lifego-dev:
    container_name: lifego-dev
    build:
      context: .
      dockerfile: Dockerfile-Dev
    env_file:
      - .env
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development

  lifego-prod:
    container_name: lifego-prod
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
