export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const EDIT_NOTIFICATION = 'EDIT_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
